# Generated by Django 6.0.4 on 2026-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('documento', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_ingreso', models.TimeField(verbose_name='Hora de ingreso')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('presente', models.BooleanField(default=False, verbose_name='¿Estuvo presente?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
